'use client';
import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

type Citation = { citation_number: number; source: string; chunk_id: number; content?: string };
type Message = { role: 'user' | 'bot'; content: string; citations?: Citation[] };

export default function ChatMessage({ msg }: { msg: Message }) {
  const isUser = msg.role === 'user';
  const [activeCite, setActiveCite] = useState<Citation | null>(null);

  const processedContent = isUser 
    ? msg.content 
    : msg.content.replace(/\[([\d,\s]+)\]/g, (match, numbers) => {
        const links = numbers.split(',').map((n: string) => {
          const num = n.trim();
          return `[${num}](#cite-${num})`;
        });
        return `[${links.join(', ')}]`;
      });

  // NEW: Filter citations to ONLY show the ones the AI actually referenced in the text
  const usedCitations = msg.citations?.filter(cite => {
    // Looks for the specific citation number anywhere inside brackets in the AI's response
    const regex = new RegExp(`\\[[^\\]]*\\b${cite.citation_number}\\b[^\\]]*\\]`);
    return regex.test(msg.content);
  }) || [];

  return (
    <div className={`p-5 rounded-2xl max-w-[85%] shadow-sm transition-all ${
      isUser 
        ? 'bg-blue-600 text-white self-end ml-auto rounded-br-sm' 
        : 'bg-white border border-slate-200 self-start text-slate-800 rounded-bl-sm shadow-md w-full'
    }`}>
      
      {isUser ? (
        <p className="whitespace-pre-wrap leading-relaxed text-[15px]">{msg.content}</p>
      ) : (
        // The 'prose' class beautifully formats headers, lists, and bold text.
        <div className="prose prose-sm prose-blue max-w-none prose-p:leading-relaxed prose-a:text-blue-600">
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            components={{
              // Intercept any link '<a>' tags generated by our regex
              a: ({ href, children }) => {
                if (href?.startsWith('#cite-')) {
                  const citeNum = parseInt(href.replace('#cite-', ''));
                  const citation = msg.citations?.find(c => c.citation_number === citeNum);
                  
                  if (!citation) return <span className="text-slate-400">{children}</span>;

                  return (
                    <button
                      onClick={() => setActiveCite(citation)}
                      className="inline-flex items-center justify-center min-w-[20px] h-5 px-1.5 ml-1 mr-0.5 text-[10px] font-bold text-blue-700 bg-blue-100 rounded-md hover:bg-blue-600 hover:text-white transition-colors cursor-pointer no-underline align-middle shadow-sm border border-blue-200"
                      title={`View source: ${citation.source}`}
                    >
                      {children}
                    </button>
                  );
                }
                // Normal links
                return <a href={href} target="_blank" rel="noopener noreferrer">{children}</a>;
              }
            }}
          >
            {processedContent}
          </ReactMarkdown>
        </div>
      )}

      {/* FIXED: The footer now maps over 'usedCitations' instead of 'msg.citations' */}
      {!isUser && usedCitations.length > 0 && (
        <div className="mt-6 pt-3 border-t border-slate-100/50 text-xs bg-slate-50/50 p-3 rounded-lg flex flex-wrap gap-2 items-center">
          <strong className="uppercase tracking-wider text-[10px] text-slate-400 mr-2">
            Sources Cited:
          </strong>
          {usedCitations.map(cite => (
             <span key={cite.citation_number} className="text-slate-500 bg-white border border-slate-200 px-2 py-1 rounded shadow-sm flex items-center gap-1">
                <span className="font-bold text-blue-600">[{cite.citation_number}]</span>
                <span className="truncate max-w-[150px]">{cite.source}</span>
             </span>
          ))}
        </div>
      )}

      {/* Pop-up Modal for Chunk Data */}
      {activeCite && (
        <div 
          className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/40 backdrop-blur-sm p-4 animate-in fade-in duration-200" 
          onClick={() => setActiveCite(null)}
        >
          <div 
            className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[85vh] flex flex-col overflow-hidden border border-slate-200 transform transition-all" 
            onClick={e => e.stopPropagation()}
          >
            <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center bg-slate-50">
              <div className="flex items-center gap-3 overflow-hidden">
                <div className="w-8 h-8 bg-blue-100 text-blue-600 rounded-lg flex items-center justify-center flex-shrink-0 text-sm">
                  📄
                </div>
                <div>
                  <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-0.5">Source Material</p>
                  <h3 className="font-bold text-slate-800 truncate text-sm">{activeCite.source}</h3>
                </div>
              </div>
              <button 
                onClick={() => setActiveCite(null)} 
                className="w-8 h-8 flex items-center justify-center rounded-full text-slate-400 hover:bg-slate-200 hover:text-slate-700 transition-colors"
              >
                ✕
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto text-[15px] text-slate-700 leading-relaxed whitespace-pre-wrap bg-white font-serif">
              {activeCite.content || "Content unavailable."}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}